---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation '
Parameters:
  S3bucket:
    Type: String
    Default: MyS3bucket
  ImageId:
    Type: String
    Default: "ami-0181f8d9b6f098ec4"
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: "vpc-1d20387a"
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: my-test-keypair
  InstanceType:
    Type: String
    Default: t2.micro
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    Default: 0.0.0.0/0
  InstanceCount:
    Default: '1'
    Description: The initial number of Instances
    Type: Number

Resources:
  InstanceInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: 
        - !Ref S3ReadRole
  S3ReadRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
  S3ReadPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3ReadPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 's3:GetObject'
            Resource: '*'
      Roles: 
        - !Ref S3ReadRole
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref SSHLocation
      VpcId:
        Ref: VpcId
  WebServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        !GetAZs eu-west-1

      LaunchConfigurationName:
        Ref: LaunchConfig
      MinSize: '1'
      MaxSize: '5'
      DesiredCapacity: !Ref InstanceCount
      Tags:
        - Key: "Name"
          Value: "MyServerName"
          PropagateAtLaunch: True
      

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceInstanceProfile
      SecurityGroups: 
      - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyName
      SpotPrice: 0.1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update && apt-get upgrade -y
          apt-get install python-dev libmysqlclient-dev python-pip -y
          pip install paramiko ansible awscli
          mkdir -p /home/ubuntu/ansible && aws s3 sync s3://${S3bucket}/ /home/ubuntu/ansible/
          ansible-playbook /home/ubuntu/ansible/playbooks/playbook.yml
